### ISSUE TITLE
causes crash in kate 18.04.3 / kde-frameworks 5.50

### ISSUE THREAD

**Issue by mpictor** [Pitmairen/kate-jinja2-highlighting#8]
Kate started crashing on me, with errors indicating problems in your syntax files:

```
$ kate configure.yml 
Fontconfig error: failed reading config file
Fontconfig error: Cannot load config file "infinality/conf.d"
org.kde.ksyntaxhighlighting: Context: Unknown format "Attribute" in context "attribute" of definition "Jinja2/YAML"
org.kde.ksyntaxhighlighting: Context: Unknown format "Attribute" in context "attribute-inline" of definition "Jinja2/YAML"
org.kde.ksyntaxhighlighting: Context: Unknown format "Attribute" in context "attribute-pre" of definition "Jinja2/YAML"
org.kde.ksyntaxhighlighting: Rule: Unknown format "Attribute" in context "attribute-pre" of definition "Jinja2/YAML"
org.kde.ksyntaxhighlighting: Context: Unknown format "Attribute" in context "attribute-pre-inline" of definition "Jinja2/YAML"
org.kde.ksyntaxhighlighting: Rule: Unknown format "Attribute" in context "attribute-pre-inline" of definition "Jinja2/YAML"
KCrash: Application 'kate' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
```
At this point, it acts as if I put it in the background with `^Z` - but I didn't.
```
[1]+  Stopped                 kate configure.yml

QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 40 and type 'Read', disabling...
Unable to start Dr. Konqi
Re-raising signal for core dump handling.

[1]+  Segmentation fault      (core dumped) kate configure.yml
```

Moving `*jinja*` out of the syntax dir prevents kate from crashing. With the files in the dir, kate works fine unless/until I open a yaml file. It doesn't seem to trigger on pure jinja2, and I don't use the css, html, or js highlighters.

Kate version is 18.04.3, from gentoo ebuild, installed in july.

Libraries:

* KDE Frameworks 5.50.0
* Qt 5.11.1 (built against 5.11.1)
* The xcb windowing system

I suspect the culprit is the kde-frameworks syntax-highlighting component; I upgraded it and other kf5 stuff to `5.50.0` two days ago.

**Comment by Pitmairen** [comment]
I'm using KDE Frameworks 5.51.0. 

I was able to make it crash by opening the template.js in the tests folder in this repo. 

This was fixed by adding the following to the itemsDatas section in the javascript-jinja2.xml:
```
<itemData name="Syntax Error"        defStyleNum="dsError" />
```

It did not crash on the yml file for me, but I got the same log entries as you. Can you try to add the following to the itemDatas section in the yaml-jinja2.xml file:
```
<itemData name="Attribute" defStyleNum="dsAttribute" />
```

**Comment by mpictor** [comment]
Thanks, that fixes it.
