### ISSUE TITLE
Else/elif blocks cause unending fold regions

### ISSUE THREAD

**Issue by sniperrifle2004** [Pitmairen/kate-jinja2-highlighting#9]
The else and elif tags start a new region. Unfortunately this causes the region of the corresponding if to not be closed (Since the endblock will be consumed by the else/elif region), causing it to expand indefinitely (In valid syntax).

I suggest to not let else and elif start a fold block at all. By far the simplest and not unreasonable imho. This is the logical equivalent of the fold rules for other blocks.

It is also possible to create a stack of regions, but this requires special treatment of the if blocks and is complicated. A third, but not as nice solution would be to let elif and else also close the region. I feel that that breaks the logical unit though.

**Comment by Pitmairen** [comment]
Yes, I can confirm the issue. I will see what I can do to fix it.

**Comment by Pitmairen** [comment]
What do you think about the fix I made in the following branch?

https://github.com/Pitmairen/kate-jinja2-highlighting/tree/fix-folding-regions

**Comment by sniperrifle2004** [comment]
Though it is not my personal preference (Since I can not fold the if statement as a whole), this does seem to be the way other languages handle it (ie. Blocks fold, not necessarily whole statements) so in that light this seems like the most logical solution.

**Comment by Pitmairen** [comment]
Yes, most of other language seems to do it this way.

**Comment by sniperrifle2004** [comment]
Then the proposed fix is fine.
